#ifndef RA_DDRAW_WRAPPER_H
#define RA_DDRAW_WRAPPER_H

#include "win32_compat.h"

#include <vector>

#define DD_OK 0
#define E_NOTIMPL ((HRESULT)-1)
#define DDERR_SURFACELOST ((HRESULT)-2000)
#define DDERR_OUTOFVIDEOMEMORY ((HRESULT)-2001)
#define DDERR_GENERIC ((HRESULT)-2002)
#define DDERR_INVALIDPARAMS ((HRESULT)-2003)
#define DDERR_WASSTILLDRAWING ((HRESULT)-2004)
#define DDERR_NOEXCLUSIVEMODE ((HRESULT)-2005)
#define DDERR_ALREADYINITIALIZED ((HRESULT)-2006)
#define DDERR_UNSUPPORTED ((HRESULT)-2007)
#define DDERR_INVALIDOBJECT ((HRESULT)-2008)
#define DDERR_OUTOFMEMORY ((HRESULT)-2009)
#define DDERR_NODIRECTDRAWSUPPORT ((HRESULT)-2010)
#define DDERR_BLTFASTCANTCLIP ((HRESULT)-2011)
#define DDERR_CANNOTATTACHSURFACE ((HRESULT)-2012)
#define DDERR_CANNOTDETACHSURFACE ((HRESULT)-2013)
#define DDERR_CANTCREATEDC ((HRESULT)-2014)
#define DDERR_CANTDUPLICATE ((HRESULT)-2015)
#define DDERR_CANTLOCKSURFACE ((HRESULT)-2016)
#define DDERR_CLIPPERISUSINGHWND ((HRESULT)-2017)
#define DDERR_COLORKEYNOTSET ((HRESULT)-2018)
#define DDERR_CURRENTLYNOTAVAIL ((HRESULT)-2019)
#define DDERR_DIRECTDRAWALREADYCREATED ((HRESULT)-2020)
#define DDERR_EXCEPTION ((HRESULT)-2021)
#define DDERR_EXCLUSIVEMODEALREADYSET ((HRESULT)-2022)
#define DDERR_HEIGHTALIGN ((HRESULT)-2023)
#define DDERR_HWNDALREADYSET ((HRESULT)-2024)
#define DDERR_HWNDSUBCLASSED ((HRESULT)-2025)
#define DDERR_IMPLICITLYCREATED ((HRESULT)-2026)
#define DDERR_INCOMPATIBLEPRIMARY ((HRESULT)-2027)
#define DDERR_INVALIDCAPS ((HRESULT)-2028)
#define DDERR_INVALIDCLIPLIST ((HRESULT)-2029)
#define DDERR_INVALIDDIRECTDRAWGUID ((HRESULT)-2030)
#define DDERR_INVALIDMODE ((HRESULT)-2031)
#define DDERR_INVALIDPIXELFORMAT ((HRESULT)-2032)
#define DDERR_INVALIDPOSITION ((HRESULT)-2033)
#define DDERR_INVALIDRECT ((HRESULT)-2034)
#define DDERR_INVALIDSURFACETYPE ((HRESULT)-2035)
#define DDERR_LOCKEDSURFACES ((HRESULT)-2036)
#define DDERR_NO3D ((HRESULT)-2037)
#define DDERR_NOALPHAHW ((HRESULT)-2038)
#define DDERR_NOANTITEARHW ((HRESULT)-2039)
#define DDERR_NOBLTHW ((HRESULT)-2040)
#define DDERR_NOBLTQUEUEHW ((HRESULT)-2041)
#define DDERR_NOCLIPLIST ((HRESULT)-2042)
#define DDERR_NOCLIPPERATTACHED ((HRESULT)-2043)
#define DDERR_NOCOLORCONVHW ((HRESULT)-2044)
#define DDERR_NOCOLORKEY ((HRESULT)-2045)
#define DDERR_NOCOLORKEYHW ((HRESULT)-2046)
#define DDERR_NOCOOPERATIVELEVELSET ((HRESULT)-2047)
#define DDERR_NODC ((HRESULT)-2048)
#define DDERR_NODDROPSHW ((HRESULT)-2049)
#define DDERR_NODIRECTDRAWHW ((HRESULT)-2050)
#define DDERR_NOEMULATION ((HRESULT)-2051)
#define DDERR_NOFLIPHW ((HRESULT)-2052)
#define DDERR_NOGDI ((HRESULT)-2053)
#define DDERR_NOHWND ((HRESULT)-2054)
#define DDERR_NOMIRRORHW ((HRESULT)-2055)
#define DDERR_NOOVERLAYDEST ((HRESULT)-2056)
#define DDERR_NOOVERLAYHW ((HRESULT)-2057)
#define DDERR_NOPALETTEATTACHED ((HRESULT)-2058)
#define DDERR_NOPALETTEHW ((HRESULT)-2059)
#define DDERR_NORASTEROPHW ((HRESULT)-2060)
#define DDERR_NOROTATIONHW ((HRESULT)-2061)
#define DDERR_NOSTRETCHHW ((HRESULT)-2062)
#define DDERR_NOT4BITCOLOR ((HRESULT)-2063)
#define DDERR_NOT4BITCOLORINDEX ((HRESULT)-2064)
#define DDERR_NOT8BITCOLOR ((HRESULT)-2065)
#define DDERR_NOTAOVERLAYSURFACE ((HRESULT)-2066)
#define DDERR_NOTEXTUREHW ((HRESULT)-2067)
#define DDERR_NOTFLIPPABLE ((HRESULT)-2068)
#define DDERR_NOTFOUND ((HRESULT)-2069)
#define DDERR_NOTLOCKED ((HRESULT)-2070)
#define DDERR_NOTPALETTIZED ((HRESULT)-2071)
#define DDERR_NOVSYNCHW ((HRESULT)-2072)
#define DDERR_NOZBUFFERHW ((HRESULT)-2073)
#define DDERR_NOZOVERLAYHW ((HRESULT)-2074)
#define DDERR_OUTOFCAPS ((HRESULT)-2075)
#define DDERR_OVERLAYCANTCLIP ((HRESULT)-2076)
#define DDERR_OVERLAYCOLORKEYONLYONEACTIVE ((HRESULT)-2077)
#define DDERR_OVERLAYNOTVISIBLE ((HRESULT)-2078)
#define DDERR_PALETTEBUSY ((HRESULT)-2079)
#define DDERR_PRIMARYSURFACEALREADYEXISTS ((HRESULT)-2080)
#define DDERR_REGIONTOOSMALL ((HRESULT)-2081)
#define DDERR_SURFACEALREADYATTACHED ((HRESULT)-2082)
#define DDERR_SURFACEALREADYDEPENDENT ((HRESULT)-2083)
#define DDERR_SURFACEBUSY ((HRESULT)-2084)
#define DDERR_SURFACEISOBSCURED ((HRESULT)-2085)
#define DDERR_SURFACENOTATTACHED ((HRESULT)-2086)
#define DDERR_TOOBIGHEIGHT ((HRESULT)-2087)
#define DDERR_TOOBIGSIZE ((HRESULT)-2088)
#define DDERR_TOOBIGWIDTH ((HRESULT)-2089)
#define DDERR_UNSUPPORTEDFORMAT ((HRESULT)-2090)
#define DDERR_UNSUPPORTEDMASK ((HRESULT)-2091)
#define DDERR_VERTICALBLANKINPROGRESS ((HRESULT)-2092)
#define DDERR_WRONGMODE ((HRESULT)-2093)
#define DDERR_XALIGN ((HRESULT)-2094)

#define DDSCL_FULLSCREEN 0x00000001U
#define DDSCL_EXCLUSIVE 0x00000010U
#define DDSCL_ALLOWMODEX 0x00000040U

#define DDSD_CAPS 0x00000001U
#define DDSD_HEIGHT 0x00000002U
#define DDSD_WIDTH 0x00000004U

#define DDSCAPS_PRIMARYSURFACE 0x00000001U
#define DDSCAPS_OFFSCREENPLAIN 0x00000002U
#define DDSCAPS_SYSTEMMEMORY 0x00000800U
#define DDSCAPS_MODEX 0x00020000U

#define DDPCAPS_8BIT 0x00000004U
#define DDPCAPS_ALLOW256 0x00000020U

#define DDLOCK_WAIT 0x00000001U

#define DDBLT_WAIT 0x00000001U
#define DDBLT_ASYNC 0x00000002U
#define DDBLT_COLORFILL 0x00000400U
#define DDBLT_KEYSRC 0x00008000U

#define DDGBS_CANBLT 0x00000001U
#define DDGBS_ISBLTDONE 0x00000002U
#define DDWAITVB_BLOCKBEGIN 0x00000001U
#define DDPSETPAL_VSYNC 0x00000001U

#define DDCAPS_BLT 0x00000001U
#define DDCAPS_BLTQUEUE 0x00000002U
#define DDCAPS_PALETTEVSYNC 0x00000004U
#define DDCAPS_BANKSWITCHED 0x00000008U
#define DDCAPS_BLTCOLORFILL 0x00000010U
#define DDCAPS_NOHARDWARE 0x00000020U
#define DDCAPS_CANBLTSYSMEM 0x00000040U

struct DDSCAPS {
    DWORD dwCaps;
};

struct DDBLTFX {
    DWORD dwSize;
    DWORD dwFillColor;
};

struct DDSURFACEDESC {
    DWORD dwSize;
    DWORD dwFlags;
    DWORD dwHeight;
    DWORD dwWidth;
    LONG lPitch;
    LPVOID lpSurface;
    DDSCAPS ddsCaps;
};

struct DDCAPS {
    DWORD dwSize;
    DWORD dwCaps;
    DWORD dwVidMemTotal;
    DWORD dwVidMemFree;
    DWORD dwSVBCaps;
    DWORD dwVSBCaps;
    DWORD dwSSBCaps;
};

class IDirectDrawPalette {
public:
    IDirectDrawPalette();
    HRESULT GetEntries(DWORD flags, DWORD start, DWORD count, PALETTEENTRY* entries);
    HRESULT SetEntries(DWORD flags, DWORD start, DWORD count, const PALETTEENTRY* entries);
    HRESULT Release();
    const PALETTEENTRY* Entries() const;
private:
    PALETTEENTRY entries_[256];
    int ref_count_;
};

class IDirectDrawSurface {
public:
    IDirectDrawSurface(int width, int height, bool primary, bool system_memory, HWND window);
    HRESULT Lock(RECT* rect, DDSURFACEDESC* desc, DWORD flags, HANDLE handle);
    HRESULT Unlock(LPVOID data);
    HRESULT Blt(RECT* dest_rect, IDirectDrawSurface* src_surface, RECT* src_rect, DWORD flags, DDBLTFX* fx);
    HRESULT GetBltStatus(DWORD flags);
    HRESULT Restore();
    HRESULT Release();
    HRESULT GetCaps(DDSCAPS* caps);
    HRESULT GetPalette(IDirectDrawPalette** palette);
    HRESULT SetPalette(IDirectDrawPalette* palette);
    HRESULT AddAttachedSurface(IDirectDrawSurface* surface);

    int Width() const;
    int Height() const;
    uint8_t* Pixels();
    const PALETTEENTRY* PaletteEntries() const;
    bool IsPrimary() const;
    bool UsesPalette(const IDirectDrawPalette* palette) const;
    HWND Window() const;
    void Present();
private:
    int width_;
    int height_;
    bool primary_;
    bool system_memory_;
    HWND window_;
    int ref_count_;
    IDirectDrawPalette* palette_;
    std::vector<uint8_t> pixels_;
};

class IDirectDraw {
public:
    IDirectDraw();
    HRESULT SetCooperativeLevel(HWND hwnd, DWORD flags);
    HRESULT SetDisplayMode(int width, int height, int bits_per_pixel);
    HRESULT CreatePalette(DWORD flags, PALETTEENTRY* entries, IDirectDrawPalette** palette, HANDLE reserved);
    HRESULT CreateSurface(DDSURFACEDESC* desc, IDirectDrawSurface** surface, HANDLE reserved);
    HRESULT GetCaps(DDCAPS* driver_caps, DDCAPS* hel_caps);
    HRESULT WaitForVerticalBlank(DWORD flags, HANDLE event_handle);
    HRESULT RestoreDisplayMode();
    HRESULT Release();

    int Width() const;
    int Height() const;
    HWND Window() const;
private:
    int width_;
    int height_;
    int bits_per_pixel_;
    HWND window_;
    int ref_count_;
};

using LPDIRECTDRAW = IDirectDraw*;
using LPDIRECTDRAW2 = IDirectDraw*;
using LPDIRECTDRAWSURFACE = IDirectDrawSurface*;
using LPDIRECTDRAWPALETTE = IDirectDrawPalette*;

extern "C" HRESULT DirectDrawCreate(LPVOID guid, LPDIRECTDRAW* direct_draw, LPVOID unknown_outer);
extern "C" void DirectDraw_Begin_Present_Batch(void);
extern "C" void DirectDraw_End_Present_Batch(void);
extern "C" void DirectDraw_Flush_Present(void);

#endif
